project:
  type: website
  output-dir: docs

website:
  title: "EnqDoc-EtatLitt-Sci"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - etatdelart-sci.qmd

format:
  html:
    theme: minty
    css: minty-vicxed.css
    toc: true



